CREATE TABLE "Order"(
    "OrderUID" INTEGER UNIQUE NOT NULL,
    "ClienUID" INTEGER NOT NULL,
    "WorkUID" INTEGER  NOT NULL,
	"Worker1UID" INTEGER  NOT NULL,
	"Worker2UID" INTEGER,
	"Material1UID" INTEGER,
	"Material1count" INTEGER,
	"Material2UID" INTEGER,
	"Material2count" INTEGER,
	"Equipment1UID" INTEGER,
	"Equipment2UID" INTEGER,
	"Date start" TEXT NOT NULL,
	"Date finish" TEXT NOT NULL,
	PRIMARY KEY ("OrderUID"),
	FOREIGN KEY ("ClienUID") REFERENCES Client (UID) ON UPDATE CASCADE,
	FOREIGN KEY ("WorkUID") REFERENCES Work (UID) ON UPDATE CASCADE
	FOREIGN KEY ("Worker1UID") REFERENCES Worker (UID) ON UPDATE CASCADE
	FOREIGN KEY ("Material1UID") REFERENCES Material (UID) ON UPDATE CASCADE,
	FOREIGN KEY ("Material2UID") REFERENCES Material (UID) ON UPDATE CASCADE,
	FOREIGN KEY ("Worker2UID") REFERENCES Worker (UID) ON UPDATE CASCADE
	FOREIGN KEY ("Equipment1UID") REFERENCES Equipment (UID) ON UPDATE CASCADE,
	FOREIGN KEY ("Equipment2UID") REFERENCES Equipment (UID) ON UPDATE CASCADE
);